name: Docker tag latest

on:
  release:
    types: [released]

env:
  version: ${GITHUB_REF_NAME#v}

concurrency:
  group: tag
  cancel-in-progress: true

jobs:
  tag:
    if: github.repository == 'navtrack/navtrack'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker tag
        run: |
          docker pull ghcr.io/navtrack/web:${{ env.version }}
          docker pull ghcr.io/navtrack/api:${{ env.version }}
          docker pull ghcr.io/navtrack/listener:${{ env.version }}
          docker tag ghcr.io/navtrack/web:${{ env.version }} ghcr.io/navtrack/web:latest
          docker tag ghcr.io/navtrack/api:${{ env.version }} ghcr.io/navtrack/api:latest
          docker tag ghcr.io/navtrack/listener:${{ env.version }} ghcr.io/navtrack/listener:latest
          docker push ghcr.io/navtrack/web -a
          docker push ghcr.io/navtrack/api -a
          docker push ghcr.io/navtrack/listener -a
